### ISSUE TITLE
Bypass doesn't work properly

### ISSUE THREAD

**Issue by Ryan00793** [MrLittleKitty/Allegiance#1]
https://github.com/MrLittleKitty/Allegiance/blob/master/src/main/java/net/arcation/allegiance/commands/AllegianceCommand.java#L42

Should be 1 not 2

**Comment by MrLittleKitty** [comment]
Fixed as of https://github.com/MrLittleKitty/Allegiance/commit/db7fbd13a40193bb9171867e464dee07e18d72ae
